"""Contract tests for the static Pages JSON generated by build_pages.py."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest
from scripts.build_pages import build

from etl.models import AppConfig, Reading
from etl.storage import connect, indicator_id, init_db, sync_indicators, upsert_reading

REQUIRED_READING_KEYS = {
    "slug",
    "date",
    "value",
    "value_published",
    "unit",
    "unit_as_published",
    "status",
    "base_gap",
    "source_date",
    "variation_pct",
}


def make_reading(iid: int, day: date, value: float) -> Reading:
    return Reading(
        indicator_id=iid,
        date=day,
        value=value,
        value_published=None,
        unit_as_published="COP",
        raw_label="label",
        raw_text="raw",
        source_date=day,
        status="ok",
        base_gap=False,
        reason=None,
        created_at="2026-10-08T00:00:00Z",
        run_id="pages-test",
    )


@pytest.fixture
def pages(tmp_path: Path, config: AppConfig) -> Path:
    db = tmp_path / "pages.db"
    conn = connect(db)
    init_db(conn)
    sync_indicators(conn, config.indicators)
    uvr = indicator_id(conn, "uvr")
    upsert_reading(conn, make_reading(uvr, date(2026, 10, 7), 419.0))
    upsert_reading(conn, make_reading(uvr, date(2026, 10, 8), 419.29))
    dolar = indicator_id(conn, "dolar_oficial_hoy")
    upsert_reading(conn, make_reading(dolar, date(2026, 10, 8), 3238.88))
    conn.close()
    out = tmp_path / "api"
    build(db, Path("config/indicators.yaml"), out)
    return out


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_contract_files_exist(pages: Path) -> None:
    assert (pages / "v1" / "indicators.json").exists()
    assert (pages / "v1" / "latest.json").exists()
    assert (pages / "v1" / "indicators" / "uvr" / "latest.json").exists()
    assert (pages / "v1" / "indicators" / "uvr" / "history.json").exists()
    assert (pages / "v1" / "indicators" / "uvr" / "variation.json").exists()


def test_catalog_shape(pages: Path) -> None:
    catalog = load(pages / "v1" / "indicators.json")
    assert "generated_at" in catalog
    assert len(catalog["indicators"]) == 18
    entry = next(item for item in catalog["indicators"] if item["slug"] == "uvr")
    assert {"slug", "source_url", "visible_label", "unit", "latest"} <= set(entry)


def test_latest_shape(pages: Path) -> None:
    latest = load(pages / "v1" / "latest.json")
    assert len(latest["indicators"]) == 18
    uvr = latest["indicators"]["uvr"]
    assert set(uvr) >= REQUIRED_READING_KEYS
    assert uvr["value"] == pytest.approx(419.29)
    assert uvr["variation_pct"] == pytest.approx((419.29 - 419.0) / 419.0 * 100)
    assert uvr["base_gap"] is False


def test_history_shape(pages: Path) -> None:
    history = load(pages / "v1" / "indicators" / "uvr" / "history.json")
    assert history["slug"] == "uvr"
    assert history["unit"] == "COP"
    assert len(history["readings"]) == 2
    assert set(history["readings"][0]) >= REQUIRED_READING_KEYS


def test_variation_shape(pages: Path) -> None:
    variation = load(pages / "v1" / "indicators" / "uvr" / "variation.json")
    assert {
        "slug",
        "date",
        "value",
        "previous_date",
        "previous_value",
        "variation_pct",
        "base_gap",
    } <= set(variation)
    assert variation["previous_date"] == "2026-10-07"


def test_indicator_without_readings(pages: Path) -> None:
    latest = load(pages / "v1" / "indicators" / "dolar_oficial_manana" / "latest.json")
    assert latest == {}
    history = load(pages / "v1" / "indicators" / "dolar_oficial_manana" / "history.json")
    assert history["readings"] == []
